# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
include: ['_pages']

# Site settings
title: "Robert's Blog"
email: robert.dolca@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robertdolca.github.io" # the base hostname & protocol for your site
social:
  github: RobertDolca
  linkedin: RobertDolca
  twitter: RobertDolca

# Build settings
markdown: kramdown

# Atom (RSS) feeds
gems:
  - jekyll-feed
